### ISSUE TITLE
adjust lemma schema

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/data-format#473]
The `lemma` property of the Lexeme schema should be structured as follows:

```yml
lemma:
  transcription: {Multi-Orthography Transcription}
  abstract:      {Boolean}
  unattested:    {Boolean}
```

This provides more information about the lemma to use when presenting it (whether to display an asterisk next to the lemma in the case of unattested/reconstructed forms, or vertical pipes for abstract forms).
