### ISSUE TITLE
Category: support category hierarchies

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/data-format#498]
The Category object should contain references or embedded data for its parent category, allowing implementations to display hierarchies of categories.

```yml
abbreviation:
  eng: v tr
name:
  eng: transitive verb
parent: # <- This is a Database Reference, so it could just be an ID instead of embedded data.
  abbreviation:
    eng: v
  name:
    eng: verb
```

On the parent, it would work in reverse:

```yml
abbreviation:
  eng: v
name:
  eng: verb
subcategories:
  - abbreviation:
      eng: v tr
    name:
      eng: transitive verb
```
